<h1>Add a new contact</h1>
    <form action="/comp1230/contacts/public/?page=contacts&action=doAdd" method="post" enctype="multipart/form-data"
          id="needs-validation" novalidate>
        <div class="form-group" >
            <label for="title">Title:</label>
            <input type="text" class="form-control" name="title" id="title" required>
            <div class="invalid-feedback">
                Please provide a title.
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col">
                <label for="firstname">First name:</label>
                <input type="text" class="form-control" name="firstname" id="firstname" required>
                <div class="invalid-feedback">
                    Please provide first name.
                </div>
            </div>
            <div class="form-group col">
                <label for="lastname">Last name:</label>
                <input type="text" class="form-control" name="lastname" id="lastname" required>
                <div class="invalid-feedback">
                    Please provide last name.
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-4">
                <label for="email">Email address:</label>
                <input type="email" class="form-control" name="email" id="email"">
            </div>
            <div class="form-group col-4">
                <label for="website">Website:</label>
                <input type="text" class="form-control" name="website" id="website"">
            </div>
        </div>
        <div class="form-group">
            <label for="cell number">Cell number:</label>
            <input type="text" name="cellnumber" class="form-control" id="cellnumber" >
            <label for="officenumber">Office number:</label>
            <input type="text" name="officenumber" class="form-control" id="officenumber"">
            <label for="homenumber">Home number:</label>
            <input type="text" name="homenumber" class="form-control" id="homenumber"">
        </div>
        <div class="form-group">
            <label for="twitter">Twitter:</label>
            <input type="twitter" name="twitter" id="twitter" class="form-control"">
            <label for="facebook">Facebook:</label>
            <input type="text" name="facebook" id="facebook" class="form-control"">
        </div>
        <div class="form-group">
            <label for="pic">Picture:</label>
            <input type="file" name="pic" id="pic" class="form-control-file"">
            <div class="form-group">
                <label for="comment">Comment:</label>
                <textarea name="comment" id="comment" class="form-control"></textarea>
            </div>
            <input type="hidden" name="id"">
            <br>
            <button type="submit" name="submit" class="btn btn-default pull-right">Submit</button>
        </div>
    </form>

